#[allow(dead_code)]
#[cfg(test)]
pub const GAMESTATE: &str = {
    r###"name="mp_Custodianship"
date="2213.12.13"
player={
	{
		name="Semantically_Invalid"
		country=0
	}
 {
		name="Mountny"
		country=1
	}
 {
		name="EveTam33"
		country=2
	}
 {
		name="mark"
		country=3
	}
 {
		name="FlayOtters"
		country=4
	}
 
}

country={
	0={
		name={
			key="Custodianship"
		}
		budget={
			current_month={
				income={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						alloys=37.056
					}
					planet_artisans={
						consumer_goods=15.44
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.66164
					}
				}
				expenses={
					none={
					}
					ships={
						energy=10.45
						alloys=2.15
					}
					ship_components={
						energy=12.9
						alloys=2.365
					}
					station_gatherers={
						energy=6
					}
					station_researchers={
						energy=7
					}
					starbase_stations={
						energy=7
					}
					starbase_buildings={
						energy=1
					}
					starbase_modules={
						energy=2
					}
					planet_buildings={
						energy=19
					}
					planet_buildings_strongholds={
						energy=1
					}
					planet_districts={
						energy=9
					}
					planet_districts_cities={
						energy=10
					}
					planet_districts_industrial={
						energy=4
					}
					planet_pop_assemblers={
						alloys=4.4
					}
					planet_researchers={
						energy=16
					}
					planet_metallurgists={
						minerals=48
					}
					planet_artisans={
						minerals=10
					}
					pop_category_bio_trophy={
						food=9
						consumer_goods=9
					}
					pop_category_drones={
						energy=46.2
					}
					armies={
						energy=6
					}
					leader_scientists={
						unity=10
					}
					leader_governors={
						unity=2
					}
				}
				balance={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					ships={
						energy=-10.45
						alloys=-2.15
					}
					ship_components={
						energy=-12.9
						alloys=-2.365
					}
					station_gatherers={
						energy=-6
					}
					station_researchers={
						energy=-7
					}
					starbase_stations={
						energy=-7
					}
					starbase_buildings={
						energy=-1
					}
					starbase_modules={
						energy=-2
					}
					planet_buildings={
						energy=-19
					}
					planet_buildings_strongholds={
						energy=-1
					}
					planet_districts={
						energy=-9
					}
					planet_districts_cities={
						energy=-10
					}
					planet_districts_industrial={
						energy=-4
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_pop_assemblers={
						alloys=-4.4
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						energy=-16
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						minerals=-48
						alloys=37.056
					}
					planet_artisans={
						minerals=-10
						consumer_goods=15.44
					}
					pop_category_bio_trophy={
						food=-9
						consumer_goods=-9
					}
					pop_category_drones={
						energy=-46.2
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					armies={
						energy=-6
					}
					leader_scientists={
						unity=-10
					}
					leader_governors={
						unity=-2
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.66164
					}
				}
				extra_income={
					none={
					}
				}
				extra_expenses={
					none={
					}
				}
				extra_balance={
					none={
					}
				}
			}
			last_month={
				income={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						alloys=37.056
					}
					planet_artisans={
						consumer_goods=15.44
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.67174
					}
				}
				expenses={
					none={
					}
					ships={
						energy=10.45
						alloys=2.15
					}
					ship_components={
						energy=12.9
						alloys=2.365
					}
					station_gatherers={
						energy=6
					}
					station_researchers={
						energy=7
					}
					starbase_stations={
						energy=7
					}
					starbase_buildings={
						energy=1
					}
					starbase_modules={
						energy=2
					}
					planet_buildings={
						energy=19
					}
					planet_buildings_strongholds={
						energy=1
					}
					planet_districts={
						energy=9
					}
					planet_districts_cities={
						energy=10
					}
					planet_districts_industrial={
						energy=4
					}
					planet_pop_assemblers={
						alloys=2.4
					}
					planet_researchers={
						energy=16
					}
					planet_metallurgists={
						minerals=48
					}
					planet_artisans={
						minerals=10
					}
					pop_category_bio_trophy={
						food=9
						consumer_goods=9
					}
					pop_category_drones={
						energy=44
					}
					armies={
						energy=6
					}
					leader_scientists={
						unity=10
					}
					leader_governors={
						unity=2
					}
				}
				balance={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					ships={
						energy=-10.45
						alloys=-2.15
					}
					ship_components={
						energy=-12.9
						alloys=-2.365
					}
					station_gatherers={
						energy=-6
					}
					station_researchers={
						energy=-7
					}
					starbase_stations={
						energy=-7
					}
					starbase_buildings={
						energy=-1
					}
					starbase_modules={
						energy=-2
					}
					planet_buildings={
						energy=-19
					}
					planet_buildings_strongholds={
						energy=-1
					}
					planet_districts={
						energy=-9
					}
					planet_districts_cities={
						energy=-10
					}
					planet_districts_industrial={
						energy=-4
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_pop_assemblers={
						alloys=-2.4
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						energy=-16
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						minerals=-48
						alloys=37.056
					}
					planet_artisans={
						minerals=-10
						consumer_goods=15.44
					}
					pop_category_bio_trophy={
						food=-9
						consumer_goods=-9
					}
					pop_category_drones={
						energy=-44
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					armies={
						energy=-6
					}
					leader_scientists={
						unity=-10
					}
					leader_governors={
						unity=-2
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.67174
					}
				}
				extra_income={
					none={
					}
				}
				extra_expenses={
					none={
					}
				}
				extra_balance={
					none={
					}
				}
			}
		}
		modules={
            standard_economy_module={
				resources={
					energy=558.0887
					minerals=2212.392
					food=1247.72
					physics_research=259.52768
					society_research=247.632
					engineering_research=253.632
					influence=494.49584
					unity=1750.93642
					consumer_goods=3097.62
					alloys=241.514
					minor_artifacts=3
				}
			}
		}
    }
}"###
};

#[allow(dead_code)]
#[cfg(test)]
pub const META: &str = {
    r###"version="Cepheus v3.4.5"
version_control_revision=95132
name="mp_Custodianship"
date="2213.12.13"
required_dlcs={
	"Ancient Relics Story Pack"
	"Anniversary Portraits"
	"Apocalypse"
	"Distant Stars Story Pack"
	"Federations"
	"Horizon Signal"
	"Humanoids Species Pack"
	"Leviathans Story Pack"
	"Lithoids Species Pack"
	"Megacorp"
	"Necroids Species Pack"
	"Nemesis"
	"Overlord"
	"Plantoids Species Pack"
	"Synthetic Dawn Story Pack"
	"Utopia"
}
player_portrait="sd_hum_robot"
flag={
	icon={
		category="human"
		file="flag_human_8.dds"
	}
	background={
		category="backgrounds"
		file="00_solid.dds"
	}
	colors={
		"blue"
		"black"
		"null"
		"null"
	}
}
meta_fleets=22
meta_planets=5
"###
};

#[allow(dead_code)]
#[cfg(test)]
pub const COMPLETE_MODEL_SERIALIZED: &str = {
    r###"{
  "campaign_name": "mp_Custodianship",
  "date": [
    2213,
    12,
    13
  ],
  "empires": [
    {
      "name": "Custodianship",
      "driver": {
        "Human": "Semantically_Invalid"
      },
      "budget": {
        "income": {
          "Energy": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_technician",
              132.32
            ],
            [
              "orbital_mining_deposits",
              19.8
            ]
          ],
          "Physics": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Engineering": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Influence": [
            [
              "country_base",
              3.0
            ],
            [
              "country_ethic",
              1.0
            ],
            [
              "country_power_projection",
              0.66164
            ]
          ],
          "Unity": [
            [
              "country_base",
              5.25
            ],
            [
              "planet_jobs",
              1.594
            ],
            [
              "planet_bio_trophies",
              43.308
            ]
          ],
          "Minerals": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_miners",
              34.896
            ],
            [
              "orbital_mining_deposits",
              25.3
            ]
          ],
          "Alloys": [
            [
              "country_base",
              5.0
            ],
            [
              "planet_metallurgists",
              37.056
            ]
          ],
          "Food": [
            [
              "planet_farmers",
              14.54
            ]
          ],
          "Society": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              5.0
            ]
          ],
          "ConsumerGoods": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_artisans",
              15.44
            ]
          ]
        },
        "expense": {
          "Alloys": [
            [
              "ships",
              2.15
            ],
            [
              "ship_components",
              2.365
            ],
            [
              "planet_pop_assemblers",
              4.4
            ]
          ],
          "Energy": [
            [
              "ships",
              10.45
            ],
            [
              "ship_components",
              12.9
            ],
            [
              "station_gatherers",
              6.0
            ],
            [
              "station_researchers",
              7.0
            ],
            [
              "starbase_stations",
              7.0
            ],
            [
              "starbase_buildings",
              1.0
            ],
            [
              "starbase_modules",
              2.0
            ],
            [
              "planet_buildings",
              19.0
            ],
            [
              "planet_buildings_strongholds",
              1.0
            ],
            [
              "planet_districts",
              9.0
            ],
            [
              "planet_districts_cities",
              10.0
            ],
            [
              "planet_districts_industrial",
              4.0
            ],
            [
              "planet_researchers",
              16.0
            ],
            [
              "pop_category_drones",
              46.2
            ],
            [
              "armies",
              6.0
            ]
          ],
          "Food": [
            [
              "pop_category_bio_trophy",
              9.0
            ]
          ],
          "ConsumerGoods": [
            [
              "pop_category_bio_trophy",
              9.0
            ]
          ],
          "Unity": [
            [
              "leader_scientists",
              10.0
            ],
            [
              "leader_governors",
              2.0
            ]
          ],
          "Minerals": [
            [
              "planet_metallurgists",
              48.0
            ],
            [
              "planet_artisans",
              10.0
            ]
          ]
        },
        "balance": {
          "Influence": [
            [
              "country_base",
              3.0
            ],
            [
              "country_ethic",
              1.0
            ],
            [
              "country_power_projection",
              0.66164
            ]
          ],
          "Minerals": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_miners",
              34.896
            ],
            [
              "planet_metallurgists",
              -48.0
            ],
            [
              "planet_artisans",
              -10.0
            ],
            [
              "orbital_mining_deposits",
              25.3
            ]
          ],
          "Food": [
            [
              "planet_farmers",
              14.54
            ],
            [
              "pop_category_bio_trophy",
              -9.0
            ]
          ],
          "Alloys": [
            [
              "country_base",
              5.0
            ],
            [
              "ships",
              -2.15
            ],
            [
              "ship_components",
              -2.365
            ],
            [
              "planet_pop_assemblers",
              -4.4
            ],
            [
              "planet_metallurgists",
              37.056
            ]
          ],
          "Society": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              5.0
            ]
          ],
          "Unity": [
            [
              "country_base",
              5.25
            ],
            [
              "planet_jobs",
              1.594
            ],
            [
              "planet_bio_trophies",
              43.308
            ],
            [
              "leader_scientists",
              -10.0
            ],
            [
              "leader_governors",
              -2.0
            ]
          ],
          "ConsumerGoods": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_artisans",
              15.44
            ],
            [
              "pop_category_bio_trophy",
              -9.0
            ]
          ],
          "Physics": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Engineering": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Energy": [
            [
              "country_base",
              30.0
            ],
            [
              "ships",
              -10.45
            ],
            [
              "ship_components",
              -12.9
            ],
            [
              "station_gatherers",
              -6.0
            ],
            [
              "station_researchers",
              -7.0
            ],
            [
              "starbase_stations",
              -7.0
            ],
            [
              "starbase_buildings",
              -1.0
            ],
            [
              "starbase_modules",
              -2.0
            ],
            [
              "planet_buildings",
              -19.0
            ],
            [
              "planet_buildings_strongholds",
              -1.0
            ],
            [
              "planet_districts",
              -9.0
            ],
            [
              "planet_districts_cities",
              -10.0
            ],
            [
              "planet_districts_industrial",
              -4.0
            ],
            [
              "planet_technician",
              132.32
            ],
            [
              "planet_researchers",
              -16.0
            ],
            [
              "pop_category_drones",
              -46.2
            ],
            [
              "orbital_mining_deposits",
              19.8
            ],
            [
              "armies",
              -6.0
            ]
          ]
        },
        "income_last_month": {
          "Alloys": [
            [
              "country_base",
              5.0
            ],
            [
              "planet_metallurgists",
              37.056
            ]
          ],
          "Unity": [
            [
              "country_base",
              5.25
            ],
            [
              "planet_jobs",
              1.594
            ],
            [
              "planet_bio_trophies",
              43.308
            ]
          ],
          "Influence": [
            [
              "country_base",
              3.0
            ],
            [
              "country_ethic",
              1.0
            ],
            [
              "country_power_projection",
              0.67174
            ]
          ],
          "ConsumerGoods": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_artisans",
              15.44
            ]
          ],
          "Energy": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_technician",
              132.32
            ],
            [
              "orbital_mining_deposits",
              19.8
            ]
          ],
          "Society": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              5.0
            ]
          ],
          "Minerals": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_miners",
              34.896
            ],
            [
              "orbital_mining_deposits",
              25.3
            ]
          ],
          "Physics": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Food": [
            [
              "planet_farmers",
              14.54
            ]
          ],
          "Engineering": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ]
        },
        "expense_last_month": {
          "Alloys": [
            [
              "country_base",
              5.0
            ],
            [
              "planet_metallurgists",
              37.056
            ]
          ],
          "Food": [
            [
              "planet_farmers",
              14.54
            ]
          ],
          "Influence": [
            [
              "country_base",
              3.0
            ],
            [
              "country_ethic",
              1.0
            ],
            [
              "country_power_projection",
              0.67174
            ]
          ],
          "Energy": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_technician",
              132.32
            ],
            [
              "orbital_mining_deposits",
              19.8
            ]
          ],
          "Engineering": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Unity": [
            [
              "country_base",
              5.25
            ],
            [
              "planet_jobs",
              1.594
            ],
            [
              "planet_bio_trophies",
              43.308
            ]
          ],
          "Minerals": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_miners",
              34.896
            ],
            [
              "orbital_mining_deposits",
              25.3
            ]
          ],
          "Physics": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Society": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              5.0
            ]
          ],
          "ConsumerGoods": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_artisans",
              15.44
            ]
          ]
        },
        "balance_last_month": {
          "Alloys": [
            [
              "country_base",
              5.0
            ],
            [
              "planet_metallurgists",
              37.056
            ]
          ],
          "Unity": [
            [
              "country_base",
              5.25
            ],
            [
              "planet_jobs",
              1.594
            ],
            [
              "planet_bio_trophies",
              43.308
            ]
          ],
          "Minerals": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_miners",
              34.896
            ],
            [
              "orbital_mining_deposits",
              25.3
            ]
          ],
          "Influence": [
            [
              "country_base",
              3.0
            ],
            [
              "country_ethic",
              1.0
            ],
            [
              "country_power_projection",
              0.67174
            ]
          ],
          "Energy": [
            [
              "country_base",
              30.0
            ],
            [
              "planet_technician",
              132.32
            ],
            [
              "orbital_mining_deposits",
              19.8
            ]
          ],
          "ConsumerGoods": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_artisans",
              15.44
            ]
          ],
          "Engineering": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Food": [
            [
              "planet_farmers",
              14.54
            ]
          ],
          "Physics": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              6.0
            ]
          ],
          "Society": [
            [
              "country_base",
              10.0
            ],
            [
              "planet_researchers",
              26.304
            ],
            [
              "orbital_research_deposits",
              5.0
            ]
          ]
        }
      },
      "resources": {
        "energy": 558.0887,
        "minerals": 2212.392,
        "food": 1247.72,
        "physics_research": 259.52768,
        "society_research": 247.632,
        "engineering_research": 253.632,
        "influence": 494.49584,
        "unity": 1750.93642,
        "consumer_goods": 3097.62,
        "alloys": 241.514,
        "volatile_motes": 0.0,
        "exotic_gases": 0.0,
        "rare_crystals": 0.0,
        "sr_living_metal": 0.0,
        "sr_zro": 0.0,
        "sr_dark_matter": 0.0
      }
    }
  ]
}"###
};

#[allow(dead_code)]
#[cfg(test)]
pub const EMPIRE_DATA_SERIALIZED: &str = {
    r###"[
  {
      "name": "Custodianship",
      "driver": {
          "Human": "Semantically_Invalid"
      },
      "budget": {
          "income": {
              "Physics": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ],
              "Minerals": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_miners",
                      34.896
                  ],
                  [
                      "orbital_mining_deposits",
                      25.3
                  ]
              ],
              "Society": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      5.0
                  ]
              ],
              "Unity": [
                  [
                      "country_base",
                      5.25
                  ],
                  [
                      "planet_jobs",
                      1.594
                  ],
                  [
                      "planet_bio_trophies",
                      43.308
                  ]
              ],
              "Food": [
                  [
                      "planet_farmers",
                      14.54
                  ]
              ],
              "ConsumerGoods": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_artisans",
                      15.44
                  ]
              ],
              "Influence": [
                  [
                      "country_base",
                      3.0
                  ],
                  [
                      "country_ethic",
                      1.0
                  ],
                  [
                      "country_power_projection",
                      0.66164
                  ]
              ],
              "Energy": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_technician",
                      132.32
                  ],
                  [
                      "orbital_mining_deposits",
                      19.8
                  ]
              ],
              "Alloys": [
                  [
                      "country_base",
                      5.0
                  ],
                  [
                      "planet_metallurgists",
                      37.056
                  ]
              ],
              "Engineering": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ]
          },
          "expense": {
              "Minerals": [
                  [
                      "planet_metallurgists",
                      48.0
                  ],
                  [
                      "planet_artisans",
                      10.0
                  ]
              ],
              "Energy": [
                  [
                      "ships",
                      10.45
                  ],
                  [
                      "ship_components",
                      12.9
                  ],
                  [
                      "station_gatherers",
                      6.0
                  ],
                  [
                      "station_researchers",
                      7.0
                  ],
                  [
                      "starbase_stations",
                      7.0
                  ],
                  [
                      "starbase_buildings",
                      1.0
                  ],
                  [
                      "starbase_modules",
                      2.0
                  ],
                  [
                      "planet_buildings",
                      19.0
                  ],
                  [
                      "planet_buildings_strongholds",
                      1.0
                  ],
                  [
                      "planet_districts",
                      9.0
                  ],
                  [
                      "planet_districts_cities",
                      10.0
                  ],
                  [
                      "planet_districts_industrial",
                      4.0
                  ],
                  [
                      "planet_researchers",
                      16.0
                  ],
                  [
                      "pop_category_drones",
                      46.2
                  ],
                  [
                      "armies",
                      6.0
                  ]
              ],
              "Food": [
                  [
                      "pop_category_bio_trophy",
                      9.0
                  ]
              ],
              "ConsumerGoods": [
                  [
                      "pop_category_bio_trophy",
                      9.0
                  ]
              ],
              "Unity": [
                  [
                      "leader_scientists",
                      10.0
                  ],
                  [
                      "leader_governors",
                      2.0
                  ]
              ],
              "Alloys": [
                  [
                      "ships",
                      2.15
                  ],
                  [
                      "ship_components",
                      2.365
                  ],
                  [
                      "planet_pop_assemblers",
                      4.4
                  ]
              ]
          },
          "balance": {
              "Physics": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ],
              "Energy": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "ships",
                      -10.45
                  ],
                  [
                      "ship_components",
                      -12.9
                  ],
                  [
                      "station_gatherers",
                      -6.0
                  ],
                  [
                      "station_researchers",
                      -7.0
                  ],
                  [
                      "starbase_stations",
                      -7.0
                  ],
                  [
                      "starbase_buildings",
                      -1.0
                  ],
                  [
                      "starbase_modules",
                      -2.0
                  ],
                  [
                      "planet_buildings",
                      -19.0
                  ],
                  [
                      "planet_buildings_strongholds",
                      -1.0
                  ],
                  [
                      "planet_districts",
                      -9.0
                  ],
                  [
                      "planet_districts_cities",
                      -10.0
                  ],
                  [
                      "planet_districts_industrial",
                      -4.0
                  ],
                  [
                      "planet_technician",
                      132.32
                  ],
                  [
                      "planet_researchers",
                      -16.0
                  ],
                  [
                      "pop_category_drones",
                      -46.2
                  ],
                  [
                      "orbital_mining_deposits",
                      19.8
                  ],
                  [
                      "armies",
                      -6.0
                  ]
              ],
              "Society": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      5.0
                  ]
              ],
              "Minerals": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_miners",
                      34.896
                  ],
                  [
                      "planet_metallurgists",
                      -48.0
                  ],
                  [
                      "planet_artisans",
                      -10.0
                  ],
                  [
                      "orbital_mining_deposits",
                      25.3
                  ]
              ],
              "Alloys": [
                  [
                      "country_base",
                      5.0
                  ],
                  [
                      "ships",
                      -2.15
                  ],
                  [
                      "ship_components",
                      -2.365
                  ],
                  [
                      "planet_pop_assemblers",
                      -4.4
                  ],
                  [
                      "planet_metallurgists",
                      37.056
                  ]
              ],
              "Influence": [
                  [
                      "country_base",
                      3.0
                  ],
                  [
                      "country_ethic",
                      1.0
                  ],
                  [
                      "country_power_projection",
                      0.66164
                  ]
              ],
              "Unity": [
                  [
                      "country_base",
                      5.25
                  ],
                  [
                      "planet_jobs",
                      1.594
                  ],
                  [
                      "planet_bio_trophies",
                      43.308
                  ],
                  [
                      "leader_scientists",
                      -10.0
                  ],
                  [
                      "leader_governors",
                      -2.0
                  ]
              ],
              "ConsumerGoods": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_artisans",
                      15.44
                  ],
                  [
                      "pop_category_bio_trophy",
                      -9.0
                  ]
              ],
              "Food": [
                  [
                      "planet_farmers",
                      14.54
                  ],
                  [
                      "pop_category_bio_trophy",
                      -9.0
                  ]
              ],
              "Engineering": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ]
          },
          "income_last_month": {
              "Unity": [
                  [
                      "country_base",
                      5.25
                  ],
                  [
                      "planet_jobs",
                      1.594
                  ],
                  [
                      "planet_bio_trophies",
                      43.308
                  ]
              ],
              "Energy": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_technician",
                      132.32
                  ],
                  [
                      "orbital_mining_deposits",
                      19.8
                  ]
              ],
              "Physics": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ],
              "ConsumerGoods": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_artisans",
                      15.44
                  ]
              ],
              "Engineering": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ],
              "Alloys": [
                  [
                      "country_base",
                      5.0
                  ],
                  [
                      "planet_metallurgists",
                      37.056
                  ]
              ],
              "Society": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      5.0
                  ]
              ],
              "Food": [
                  [
                      "planet_farmers",
                      14.54
                  ]
              ],
              "Minerals": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_miners",
                      34.896
                  ],
                  [
                      "orbital_mining_deposits",
                      25.3
                  ]
              ],
              "Influence": [
                  [
                      "country_base",
                      3.0
                  ],
                  [
                      "country_ethic",
                      1.0
                  ],
                  [
                      "country_power_projection",
                      0.67174
                  ]
              ]
          },
          "expense_last_month": {
              "Energy": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_technician",
                      132.32
                  ],
                  [
                      "orbital_mining_deposits",
                      19.8
                  ]
              ],
              "Society": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      5.0
                  ]
              ],
              "Alloys": [
                  [
                      "country_base",
                      5.0
                  ],
                  [
                      "planet_metallurgists",
                      37.056
                  ]
              ],
              "Food": [
                  [
                      "planet_farmers",
                      14.54
                  ]
              ],
              "Physics": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ],
              "Unity": [
                  [
                      "country_base",
                      5.25
                  ],
                  [
                      "planet_jobs",
                      1.594
                  ],
                  [
                      "planet_bio_trophies",
                      43.308
                  ]
              ],
              "Minerals": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_miners",
                      34.896
                  ],
                  [
                      "orbital_mining_deposits",
                      25.3
                  ]
              ],
              "ConsumerGoods": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_artisans",
                      15.44
                  ]
              ],
              "Influence": [
                  [
                      "country_base",
                      3.0
                  ],
                  [
                      "country_ethic",
                      1.0
                  ],
                  [
                      "country_power_projection",
                      0.67174
                  ]
              ],
              "Engineering": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ]
          },
          "balance_last_month": {
              "Unity": [
                  [
                      "country_base",
                      5.25
                  ],
                  [
                      "planet_jobs",
                      1.594
                  ],
                  [
                      "planet_bio_trophies",
                      43.308
                  ]
              ],
              "Engineering": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ],
              "Physics": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      6.0
                  ]
              ],
              "Energy": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_technician",
                      132.32
                  ],
                  [
                      "orbital_mining_deposits",
                      19.8
                  ]
              ],
              "Food": [
                  [
                      "planet_farmers",
                      14.54
                  ]
              ],
              "ConsumerGoods": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_artisans",
                      15.44
                  ]
              ],
              "Influence": [
                  [
                      "country_base",
                      3.0
                  ],
                  [
                      "country_ethic",
                      1.0
                  ],
                  [
                      "country_power_projection",
                      0.67174
                  ]
              ],
              "Society": [
                  [
                      "country_base",
                      10.0
                  ],
                  [
                      "planet_researchers",
                      26.304
                  ],
                  [
                      "orbital_research_deposits",
                      5.0
                  ]
              ],
              "Alloys": [
                  [
                      "country_base",
                      5.0
                  ],
                  [
                      "planet_metallurgists",
                      37.056
                  ]
              ],
              "Minerals": [
                  [
                      "country_base",
                      30.0
                  ],
                  [
                      "planet_miners",
                      34.896
                  ],
                  [
                      "orbital_mining_deposits",
                      25.3
                  ]
              ]
          }
      },
      "resources": {
          "energy": 558.0887,
          "minerals": 2212.392,
          "food": 1247.72,
          "physics_research": 259.52768,
          "society_research": 247.632,
          "engineering_research": 253.632,
          "influence": 494.49584,
          "unity": 1750.93642,
          "consumer_goods": 3097.62,
          "alloys": 241.514,
          "volatile_motes": 0.0,
          "exotic_gases": 0.0,
          "rare_crystals": 0.0,
          "sr_living_metal": 0.0,
          "sr_zro": 0.0,
          "sr_dark_matter": 0.0
      }
  }
]"###
};
