#[cfg(test)]
pub const GAMESTATE: &str = r###"name="mp_Custodianship"
date="2213.12.13"
player={
	{
		name="Semantically_Invalid"
		country=0
	}
 {
		name="Mountny"
		country=1
	}
 {
		name="EveTam33"
		country=2
	}
 {
		name="mark"
		country=3
	}
 {
		name="FlayOtters"
		country=4
	}
 
}

country={
	0={
		name={
			key="Custodianship"
		}
		budget={
			current_month={
				income={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						alloys=37.056
					}
					planet_artisans={
						consumer_goods=15.44
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.66164
					}
				}
				expenses={
					none={
					}
					ships={
						energy=10.45
						alloys=2.15
					}
					ship_components={
						energy=12.9
						alloys=2.365
					}
					station_gatherers={
						energy=6
					}
					station_researchers={
						energy=7
					}
					starbase_stations={
						energy=7
					}
					starbase_buildings={
						energy=1
					}
					starbase_modules={
						energy=2
					}
					planet_buildings={
						energy=19
					}
					planet_buildings_strongholds={
						energy=1
					}
					planet_districts={
						energy=9
					}
					planet_districts_cities={
						energy=10
					}
					planet_districts_industrial={
						energy=4
					}
					planet_pop_assemblers={
						alloys=4.4
					}
					planet_researchers={
						energy=16
					}
					planet_metallurgists={
						minerals=48
					}
					planet_artisans={
						minerals=10
					}
					pop_category_bio_trophy={
						food=9
						consumer_goods=9
					}
					pop_category_drones={
						energy=46.2
					}
					armies={
						energy=6
					}
					leader_scientists={
						unity=10
					}
					leader_governors={
						unity=2
					}
				}
				balance={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					ships={
						energy=-10.45
						alloys=-2.15
					}
					ship_components={
						energy=-12.9
						alloys=-2.365
					}
					station_gatherers={
						energy=-6
					}
					station_researchers={
						energy=-7
					}
					starbase_stations={
						energy=-7
					}
					starbase_buildings={
						energy=-1
					}
					starbase_modules={
						energy=-2
					}
					planet_buildings={
						energy=-19
					}
					planet_buildings_strongholds={
						energy=-1
					}
					planet_districts={
						energy=-9
					}
					planet_districts_cities={
						energy=-10
					}
					planet_districts_industrial={
						energy=-4
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_pop_assemblers={
						alloys=-4.4
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						energy=-16
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						minerals=-48
						alloys=37.056
					}
					planet_artisans={
						minerals=-10
						consumer_goods=15.44
					}
					pop_category_bio_trophy={
						food=-9
						consumer_goods=-9
					}
					pop_category_drones={
						energy=-46.2
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					armies={
						energy=-6
					}
					leader_scientists={
						unity=-10
					}
					leader_governors={
						unity=-2
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.66164
					}
				}
				extra_income={
					none={
					}
				}
				extra_expenses={
					none={
					}
				}
				extra_balance={
					none={
					}
				}
			}
			last_month={
				income={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						alloys=37.056
					}
					planet_artisans={
						consumer_goods=15.44
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.67174
					}
				}
				expenses={
					none={
					}
					ships={
						energy=10.45
						alloys=2.15
					}
					ship_components={
						energy=12.9
						alloys=2.365
					}
					station_gatherers={
						energy=6
					}
					station_researchers={
						energy=7
					}
					starbase_stations={
						energy=7
					}
					starbase_buildings={
						energy=1
					}
					starbase_modules={
						energy=2
					}
					planet_buildings={
						energy=19
					}
					planet_buildings_strongholds={
						energy=1
					}
					planet_districts={
						energy=9
					}
					planet_districts_cities={
						energy=10
					}
					planet_districts_industrial={
						energy=4
					}
					planet_pop_assemblers={
						alloys=2.4
					}
					planet_researchers={
						energy=16
					}
					planet_metallurgists={
						minerals=48
					}
					planet_artisans={
						minerals=10
					}
					pop_category_bio_trophy={
						food=9
						consumer_goods=9
					}
					pop_category_drones={
						energy=44
					}
					armies={
						energy=6
					}
					leader_scientists={
						unity=10
					}
					leader_governors={
						unity=2
					}
				}
				balance={
					none={
					}
					country_base={
						energy=30
						minerals=30
						physics_research=10
						society_research=10
						engineering_research=10
						influence=3
						unity=5.25
						consumer_goods=10
						alloys=5
					}
					ships={
						energy=-10.45
						alloys=-2.15
					}
					ship_components={
						energy=-12.9
						alloys=-2.365
					}
					station_gatherers={
						energy=-6
					}
					station_researchers={
						energy=-7
					}
					starbase_stations={
						energy=-7
					}
					starbase_buildings={
						energy=-1
					}
					starbase_modules={
						energy=-2
					}
					planet_buildings={
						energy=-19
					}
					planet_buildings_strongholds={
						energy=-1
					}
					planet_districts={
						energy=-9
					}
					planet_districts_cities={
						energy=-10
					}
					planet_districts_industrial={
						energy=-4
					}
					planet_jobs={
						unity=1.594
					}
					planet_bio_trophies={
						unity=43.308
					}
					planet_pop_assemblers={
						alloys=-2.4
					}
					planet_farmers={
						food=14.54
					}
					planet_miners={
						minerals=34.896
					}
					planet_technician={
						energy=132.32
					}
					planet_researchers={
						energy=-16
						physics_research=26.304
						society_research=26.304
						engineering_research=26.304
					}
					planet_metallurgists={
						minerals=-48
						alloys=37.056
					}
					planet_artisans={
						minerals=-10
						consumer_goods=15.44
					}
					pop_category_bio_trophy={
						food=-9
						consumer_goods=-9
					}
					pop_category_drones={
						energy=-44
					}
					orbital_mining_deposits={
						energy=19.8
						minerals=25.3
					}
					orbital_research_deposits={
						physics_research=6
						society_research=5
						engineering_research=6
					}
					armies={
						energy=-6
					}
					leader_scientists={
						unity=-10
					}
					leader_governors={
						unity=-2
					}
					country_ethic={
						influence=1
					}
					country_power_projection={
						influence=0.67174
					}
				}
				extra_income={
					none={
					}
				}
				extra_expenses={
					none={
					}
				}
				extra_balance={
					none={
					}
				}
			}
		}
		modules={
            standard_economy_module={
				resources={
					energy=558.0887
					minerals=2212.392
					food=1247.72
					physics_research=259.52768
					society_research=247.632
					engineering_research=253.632
					influence=494.49584
					unity=1750.93642
					consumer_goods=3097.62
					alloys=241.514
					minor_artifacts=3
				}
			}
		}
    }
}"###;
