[package]
name = "int_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
campaign_controller= {path = "../campaign_controller"}
crossbeam = "0.8"
actix-rt ="2.7"